<?php

namespace AppBundle\Repository;

/**
 * ClientCreditRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ClientCreditRepository extends \Doctrine\ORM\EntityRepository
{
}
