<?php

namespace AppBundle\Repository;

/**
 * ConjoinClientCreditRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ConjoinClientCreditRepository extends \Doctrine\ORM\EntityRepository
{
}
