<?php

namespace AppBundle\Repository;

/**
 * DossierAchatRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DossierAchatRepository extends \Doctrine\ORM\EntityRepository
{
}
