<?php

namespace AppBundle\Repository;

/**
 * IdentiteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class IdentiteRepository extends \Doctrine\ORM\EntityRepository
{
}
