<?php

namespace AppBundle\Repository;

/**
 * RessourceConjointRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RessourceConjointRepository extends \Doctrine\ORM\EntityRepository
{
}
