<?php

namespace AppBundle\Repository;

/**
 * RessourceClientRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RessourceClientRepository extends \Doctrine\ORM\EntityRepository
{
}
