<?php

namespace AppBundle\Repository;

/**
 * TestClientParPaysRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TestClientParPaysRepository extends \Doctrine\ORM\EntityRepository
{
}
